import { useEffect, useState } from "react";
import { repo } from "../firestore/repo";
import header from "../public/header";
import Quotes from "../components/quotes";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [isLoading, setLoading] = useState(true);
  const [quotes, setQuotes] = useState([]);
  const [allData, setAllData] = useState([]);

  const fetchQuotes = async () => {
    const apiResponse = await fetch(
      `https://api.chucknorris.io/jokes/search?query=hand`
    );
    const quotesList = await apiResponse.json();
    setQuotes(quotesList.result);
  };

  const fetchQuotesData = async () => {
    await repo.getData().then((response) => setAllData(response));
    setLoading(false);
  };

  async function handleClick(id, count) {
    await repo.incrementCount(id, count);
    fetchQuotesData();
  }

  async function handleSubmit(id, input, username, count) {
    await repo.addComment(id, input, username, count);
    fetchQuotesData();
  }

  useEffect(() => {
    fetchQuotesData();
    fetchQuotes();
  }, []);

  useEffect(() => {}, [allData, handleClick, handleSubmit]);

  return (
    <div>
      <Head>
        <title>Chuck Quote Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading ? (
        <div className={styles.loadingContainer}>
          <p className={styles.loadingText}>LOADING...</p>
        </div>
      ) : (
        <main className={styles.main}>
          <p></p>
          <div className={styles.header}>
            {header.map((x, i) => (
              <p className={x.name} key={i}>
                {x.letter}
              </p>
            ))}
          </div>
          <Quotes
            quotes={quotes}
            linkedData={allData}
            handleSubmit={handleSubmit}
            handleClick={handleClick}
          />
        </main>
      )}
    </div>
  );
}
