import { useEffect, useState } from "react";
import Quotes from "./quotes";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [quotes, setQuotes] = useState([]);
  const [isLoading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      const apiResponse = await fetch(
        `https://api.chucknorris.io/jokes/search?query=hand`
      );
      const quotesList = await apiResponse.json();
      setQuotes(quotesList.result);
      setLoading(false);
    };

    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isLoading ? <p>Loading...</p> : <Quotes quotes={quotes} />}
      </main>
    </div>
  );
}
